import type { QACategory, QAChecklistItem } from './types';

export const QA_CATEGORIES: QACategory[] = [
  {
    id: 'security',
    name: '1. Core Security Checks',
    shortName: 'Security',
    iconName: 'Shield',
    description: 'Secrets, auth enforcement, injection protection, rate limiting, and server-side guards.',
  },
  {
    id: 'func-auth',
    name: '2. Registration & Authentication',
    shortName: 'Auth Flow',
    iconName: 'UserCheck',
    description: 'Account signup, Philippine ID verification, biometrics, approval gating, and passwords.',
  },
  {
    id: 'func-admin',
    name: '3. Admin Approval Workflow',
    shortName: 'Approvals',
    iconName: 'ShieldCheck',
    description: 'Pending applicant review, approve/reject/retry decisions, and applicant notification dispatch.',
  },
  {
    id: 'func-posts',
    name: '4. Posts & Community Items',
    shortName: 'Posts',
    iconName: 'Package',
    description: 'Item creation, image uploads, thumbnails, search, filters, location tagging, and removal.',
  },
  {
    id: 'func-requests',
    name: '5. Requests & Barter Donations',
    shortName: 'Requests',
    iconName: 'HandHeart',
    description: 'Donation claims, conversation linking, poster notification, and status updates.',
  },
  {
    id: 'func-messaging',
    name: '6. Direct Messaging (Two-User Flow)',
    shortName: 'Messaging',
    iconName: 'MessageSquare',
    description: 'Real-time chat, typing indicators, presence, reactions, 5-minute unsend/edit windows.',
  },
  {
    id: 'func-notifications',
    name: '7. Email & System Notifications',
    shortName: 'Notifications',
    iconName: 'Bell',
    description: 'Live transactional emails received in inbox: approvals, messages, resets, suspensions.',
  },
  {
    id: 'func-reports',
    name: '8. Moderation & Reports',
    shortName: 'Reports',
    iconName: 'AlertOctagon',
    description: 'Submitting community reports, admin moderation review, dismissal, and content removal.',
  },
  {
    id: 'database',
    name: '9. Database & Integrity',
    shortName: 'Database',
    iconName: 'Database',
    description: 'Production schema integrity, foreign keys, credential isolation, and automated backups.',
  },
  {
    id: 'admin-security',
    name: '10. Admin Access & RBAC Guards',
    shortName: 'RBAC',
    iconName: 'Lock',
    description: 'Strict role verification preventing privilege escalation, API bypass, and student-admin boundaries.',
  },
  {
    id: 'ui-ux',
    name: '11. Responsive UI / UX Testing',
    shortName: 'UI / UX',
    iconName: 'Smartphone',
    description: 'Desktop (1280/1440/1920), tablet (768/1024), and mobile (320/375/390/412) layout validation.',
  },
  {
    id: 'states',
    name: '12. Loading, Empty & Error States',
    shortName: 'States',
    iconName: 'Layers',
    description: 'Graceful UX for slow network, server errors, empty queries, and offline disconnection.',
  },
  {
    id: 'production',
    name: '13. Production Environment Checks',
    shortName: 'Production',
    iconName: 'Server',
    description: 'Debug mode disabled, production URLs, CORS, HTTPS enforcement, and secret hygiene.',
  },
  {
    id: 'performance',
    name: '14. Performance & Resource Limits',
    shortName: 'Performance',
    iconName: 'Zap',
    description: 'Compressed media, upload caps, efficient queries, and payload optimization.',
  },
  {
    id: 'seo',
    name: '15. SEO & Web Standards',
    shortName: 'SEO',
    iconName: 'Globe',
    description: 'Page titles, meta descriptions, favicon, heading hierarchy, robots.txt, sitemap, 404.',
  },
  {
    id: 'final-check',
    name: '16. Pre-Flight Final Signoff',
    shortName: 'Final Signoff',
    iconName: 'Rocket',
    description: 'Executive review, release tag verification, and stakeholder deployment greenlight.',
  },
];

export const QA_CHECKLIST_ITEMS: QAChecklistItem[] = [
  // ==========================================
  // 1. SECURITY (20 items)
  // ==========================================
  {
    id: 'sec-hide-api-keys',
    category: 'security',
    priority: 'critical',
    title: 'Hide API Keys',
    description: 'Verify secret API keys are NOT exposed in frontend bundles or public repositories.',
    guide: 'Check frontend bundle inspect for GOOGLE_MAPS or backend secrets. Ensure VITE_ prefixes are only used for public keys.',
  },
  {
    id: 'sec-purge-git-secrets',
    category: 'security',
    priority: 'critical',
    title: 'Purge Git Secrets',
    description: 'Audit Git commit history for accidentally committed credentials, tokens, or passwords.',
    guide: 'Run git log to confirm no previous commits contain production credentials. Ensure .env is completely gitignored.',
  },
  {
    id: 'sec-use-public-db-key',
    category: 'security',
    priority: 'critical',
    title: 'Use Public DB Key Safely',
    description: 'Ensure no client-side direct database connections exist and only backend ORM accesses DB.',
    guide: 'Frontend must only talk via FastAPI /api endpoints. No client MySQL credentials.',
  },
  {
    id: 'sec-enable-rls',
    category: 'security',
    priority: 'critical',
    title: 'Enable Row-Level Security / Ownership Controls',
    description: 'Enforce database records can only be mutated according to the authenticated user.',
    guide: 'Verify update_item and delete_item check item.owner_id matches caller userId or admin role.',
  },
  {
    id: 'sec-encrypt-sensitive-data',
    category: 'security',
    priority: 'critical',
    title: 'Encrypt Sensitive Data in Transit & at Rest',
    description: 'Protect passwords, verification documents, and API communications using TLS and encryption.',
    guide: 'Verify HTTPS/TLS on API & SMTP endpoints and check hashed values in MySQL.',
  },
  {
    id: 'sec-server-side-auth',
    category: 'security',
    priority: 'critical',
    title: 'Enforce Server-Side Authentication',
    description: 'Never rely solely on frontend authentication guards; all backend endpoints must independently validate.',
    guide: 'Attempt direct curl/postman calls to admin/user endpoints without session to confirm 401/403 rejections.',
  },
  {
    id: 'sec-lock-record-access',
    category: 'security',
    priority: 'critical',
    title: 'Lock Record Access',
    description: 'Users must not be able to access, modify, or delete another user’s items, messages, or reports.',
    guide: 'Test modifying item ID belonging to user A using user B credentials.',
  },
  {
    id: 'sec-block-field-tampering',
    category: 'security',
    priority: 'critical',
    title: 'Block Field Tampering (Mass Assignment)',
    description: 'Prevent users from manipulating protected fields (role, user_id, status, is_admin, account_status).',
    guide: 'Confirm Pydantic schemas disallow clients from injecting role="admin" during registration or profile updates.',
  },
  {
    id: 'sec-secure-cookies',
    category: 'security',
    priority: 'important',
    title: 'Secure Session Cookies & Local Storage',
    description: 'Verify appropriate HttpOnly, Secure, and SameSite settings if cookies are used, or sanitized localStorage.',
    guide: 'Ensure token storage cannot be accessed via malicious third-party scripts.',
  },
  {
    id: 'sec-hash-passwords',
    category: 'security',
    priority: 'critical',
    title: 'Hash Passwords with Salted Bcrypt',
    description: 'Passwords must never be stored in plain text under any circumstances.',
    guide: 'Inspect database user table: all password_hash entries must begin with $2b$12$ or $2a$.',
  },
  {
    id: 'sec-rate-limiting',
    category: 'security',
    priority: 'critical',
    title: 'Rate Limit Login & Sensitive Endpoints',
    description: 'Protect login, registration, password reset, messaging, and upload endpoints from brute-force/DDoS.',
    guide: 'Trigger rapid login requests; verify SlowAPI triggers 429 Too Many Requests after 5 attempts/min.',
  },
  {
    id: 'sec-bot-protection',
    category: 'security',
    priority: 'important',
    title: 'Add Bot Protection & Form Guardrails',
    description: 'Protect registration, login, password reset, and public forms from automated spam bots.',
    guide: 'Verify rate limiting, submission throttling, and input length checks on registration forms.',
  },
  {
    id: 'sec-parameterize-queries',
    category: 'security',
    priority: 'critical',
    title: 'Parameterize Queries (SQL Injection Prevention)',
    description: 'Ensure all SQL operations use SQLAlchemy ORM or parameterized query bindings without string concatenation.',
    guide: 'Verify no raw f-string SQL queries exist in backend codebase.',
  },
  {
    id: 'sec-validate-inputs',
    category: 'security',
    priority: 'critical',
    title: 'Validate All Server-Side Inputs',
    description: 'Strictly validate all user inputs against Pydantic DTO models on the server.',
    guide: 'Test sending malformed payloads, negative numbers, or invalid email formats; confirm 422 Unprocessable Entity.',
  },
  {
    id: 'sec-escape-user-content',
    category: 'security',
    priority: 'critical',
    title: 'Escape User Content (XSS Prevention)',
    description: 'Prevent XSS in posts, chat messages, user bios, search terms, and comments.',
    guide: 'Submit <script>alert(1)</script> in item title, chat, and bio; verify it is safely escaped as text.',
  },
  {
    id: 'sec-restrict-file-uploads',
    category: 'security',
    priority: 'critical',
    title: 'Restrict File Uploads (Type, Size, Magic Bytes)',
    description: 'Validate file type, size, extension, and content headers. Prevent executable or SVG script uploads.',
    guide: 'Attempt uploading a .exe or .php renamed to .jpg; confirm magic byte check rejects it.',
  },
  {
    id: 'sec-trim-api-responses',
    category: 'security',
    priority: 'important',
    title: 'Trim API Responses (No Secret Leakage)',
    description: 'APIs must only return data needed by the client. Never expose password_hash or internal keys.',
    guide: 'Inspect /api/auth/login and /api/items responses in DevTools Network tab to confirm password_hash is omitted.',
  },
  {
    id: 'sec-security-headers',
    category: 'security',
    priority: 'important',
    title: 'Add HTTP Security Headers',
    description: 'Configure X-Content-Type-Options: nosniff, X-Frame-Options: DENY, HSTS, and Referrer-Policy.',
    guide: 'Check response headers in Network tab: confirm nosniff, DENY, and Referrer-Policy are present.',
  },
  {
    id: 'sec-force-https',
    category: 'security',
    priority: 'critical',
    title: 'Force HTTPS in Production',
    description: 'Ensure all production traffic redirects to HTTPS with HSTS headers enabled.',
    guide: 'Test accessing http:// version of production domain; confirm 301/308 redirect to https://.',
  },
  {
    id: 'sec-scan-dependencies',
    category: 'security',
    priority: 'important',
    title: 'Scan Dependencies for Known Vulnerabilities',
    description: 'Verify both frontend (npm audit) and backend (pip-audit) report 0 vulnerabilities.',
    guide: 'Run npm audit and pip-audit; confirm clean bills of health with no critical/high advisories.',
  },

  // ==========================================
  // 2. FUNCTIONALITY: REGISTRATION & AUTH (12 items)
  // ==========================================
  {
    id: 'auth-register-account',
    category: 'func-auth',
    priority: 'critical',
    title: 'Register New Account',
    description: 'User can register with full name, email, phone, municipality, barangay, and password.',
    guide: 'Complete registration form on /register and verify user record is created in MySQL.',
  },
  {
    id: 'auth-required-fields',
    category: 'func-auth',
    priority: 'critical',
    title: 'Required Fields Validation',
    description: 'All mandatory fields in the registration form display red error messages when submitted empty.',
    guide: 'Click submit on an empty registration form; confirm errors appear and form submission is blocked.',
  },
  {
    id: 'auth-ph-id-validation',
    category: 'func-auth',
    priority: 'critical',
    title: 'Philippine ID Information Validation',
    description: 'Government ID selection (PhilSys, UMID, Driver’s License, Passport, etc.) and number formatting work.',
    guide: 'Select different ID types and input valid ID numbers; ensure masked ID formatting works correctly.',
  },
  {
    id: 'auth-facial-verification',
    category: 'func-auth',
    priority: 'important',
    title: 'Facial Verification Workflow',
    description: 'Camera capture or selfie upload works, previews correctly, and verifies liveness.',
    guide: 'Complete biometric selfie capture step; confirm selfie photo preview renders and saves.',
  },
  {
    id: 'auth-pending-status',
    category: 'func-auth',
    priority: 'critical',
    title: 'Newly Registered User Remains "Pending"',
    description: 'All newly registered users are assigned PENDING status and redirected to Pending Verification page.',
    guide: 'After registration, verify account_status_id=1 (PENDING) in DB and user sees waiting screen.',
  },
  {
    id: 'auth-cannot-bypass-approval',
    category: 'func-auth',
    priority: 'critical',
    title: 'User Cannot Bypass Admin Approval',
    description: 'Attempting to log in as a PENDING or REJECTED user returns HTTP 403 Forbidden with clear message.',
    guide: 'Try logging into newly registered pending account; verify sign-in is blocked until approved.',
  },
  {
    id: 'auth-login-works',
    category: 'func-auth',
    priority: 'critical',
    title: 'Approved User Login Works',
    description: 'Approved users can sign in with email and password and are redirected to Community Dashboard.',
    guide: 'Sign in with an APPROVED account; verify successful session creation and dashboard load.',
  },
  {
    id: 'auth-logout-works',
    category: 'func-auth',
    priority: 'critical',
    title: 'User Logout Works & Clears Session',
    description: 'Clicking logout clears authentication state, removes cached credentials, and redirects to /login.',
    guide: 'Click logout in profile menu; confirm navigation to /login and backward button does not re-authenticate.',
  },
  {
    id: 'auth-forgot-password',
    category: 'func-auth',
    priority: 'critical',
    title: 'Forgot Password Request Works',
    description: 'Entering registered email sends password reset token without enumerating account existence.',
    guide: 'Submit email on /forgot-password; verify generic success message and reset token generated in DB.',
  },
  {
    id: 'auth-reset-email-received',
    category: 'func-auth',
    priority: 'critical',
    title: 'Password Reset Email Is Received',
    description: 'Verify password reset link is delivered to inbox with valid token parameter.',
    guide: 'Check mailbox for BayanihanHub password reset email; click the reset button.',
  },
  {
    id: 'auth-expired-reset-rejected',
    category: 'func-auth',
    priority: 'important',
    title: 'Expired Reset Links Are Rejected',
    description: 'Reset tokens older than 1 hour or previously marked as used must return an error.',
    guide: 'Test using an expired or already used token; confirm reset is rejected.',
  },
  {
    id: 'auth-invalid-reset-rejected',
    category: 'func-auth',
    priority: 'important',
    title: 'Invalid Reset Links Are Rejected',
    description: 'Submitting a corrupted or fabricated token returns HTTP 400 Bad Request.',
    guide: 'Navigate to /reset-password?token=invalid-fake-token; confirm error is shown.',
  },

  // ==========================================
  // 3. FUNCTIONALITY: ADMIN APPROVAL (7 items)
  // ==========================================
  {
    id: 'admin-pending-users-appear',
    category: 'func-admin',
    priority: 'critical',
    title: 'Pending Users Appear in Admin Dashboard',
    description: 'Administrator can view list of pending neighbor applications with photos and ID documents.',
    guide: 'Navigate to /admin/approvals; confirm pending applicants render with details and preview modal.',
  },
  {
    id: 'admin-can-approve-user',
    category: 'func-admin',
    priority: 'critical',
    title: 'Admin Can Approve Applicant',
    description: 'Clicking "Approve" transitions user status to APPROVED and unlocks full community access.',
    guide: 'Approve a test pending applicant; verify status changes to APPROVED and user can now sign in.',
  },
  {
    id: 'admin-can-reject-user',
    category: 'func-admin',
    priority: 'critical',
    title: 'Admin Can Reject Applicant',
    description: 'Admin can reject an application with an optional reason; user status updates to REJECTED.',
    guide: 'Reject a test applicant with a note; verify user status updates and sign-in remains blocked.',
  },
  {
    id: 'admin-can-request-retry',
    category: 'func-admin',
    priority: 'important',
    title: 'Admin Can Request Verification Retry',
    description: 'Admin can request clearer document photos; applicant receives retry instructions.',
    guide: 'Click "Request Resubmission" in admin verification modal; confirm status updates.',
  },
  {
    id: 'admin-approved-can-login',
    category: 'func-admin',
    priority: 'critical',
    title: 'Approved User Can Log In Immediately',
    description: 'Once approved by admin, the neighbor can log in immediately with original credentials.',
    guide: 'Log in with freshly approved user account; verify seamless access to dashboard.',
  },
  {
    id: 'admin-rejected-cannot-access',
    category: 'func-admin',
    priority: 'critical',
    title: 'Rejected User Cannot Access Protected Features',
    description: 'Attempting to login or call authenticated endpoints returns clear rejection message.',
    guide: 'Verify rejected account receives 403 Forbidden with contact administrator notice.',
  },
  {
    id: 'admin-approval-email-sent',
    category: 'func-admin',
    priority: 'critical',
    title: 'User Receives Email Notification Upon Decision',
    description: 'Approval or rejection triggers background email notification to the user’s registered email address.',
    guide: 'Confirm welcome/approval email is received in user inbox with login button.',
  },

  // ==========================================
  // 4. FUNCTIONALITY: POSTS & ITEMS (12 items)
  // ==========================================
  {
    id: 'posts-create-post',
    category: 'func-posts',
    priority: 'critical',
    title: 'Create Item Posting',
    description: 'User can post an item with title, description, category, condition, quantity, and pickup options.',
    guide: 'Create new donation item from /post-item; verify item displays on /browse immediately.',
  },
  {
    id: 'posts-edit-own-post',
    category: 'func-posts',
    priority: 'critical',
    title: 'Edit Own Post',
    description: 'Owner can update item title, description, category, condition, and status.',
    guide: 'Edit posting from item details page; confirm changes persist in database.',
  },
  {
    id: 'posts-delete-own-post',
    category: 'func-posts',
    priority: 'critical',
    title: 'Delete Own Post (Soft-Delete)',
    description: 'Owner can delete their posting; item status updates to "removed" and vanishes from browse.',
    guide: 'Delete test post; confirm it no longer appears in public browse feed.',
  },
  {
    id: 'posts-view-post',
    category: 'func-posts',
    priority: 'critical',
    title: 'View Item Details Page',
    description: 'Public and authenticated users can view full item details, photos, owner profile, and location.',
    guide: 'Open item details page /items/:id; confirm all fields, tags, and carousel render.',
  },
  {
    id: 'posts-search-posts',
    category: 'func-posts',
    priority: 'important',
    title: 'Search Posts by Keyword',
    description: 'Typing keywords in search bar filters items by title, description, and tags.',
    guide: 'Search for specific item title; verify only matching items are displayed.',
  },
  {
    id: 'posts-filter-posts',
    category: 'func-posts',
    priority: 'important',
    title: 'Filter Posts by Category, Condition & Type',
    description: 'Category dropdowns and filter pills accurately filter the browse feed.',
    guide: 'Select "Electronics" or "Furniture"; confirm only matching category items render.',
  },
  {
    id: 'posts-upload-image',
    category: 'func-posts',
    priority: 'critical',
    title: 'Upload Item Photo',
    description: 'User can select and upload photos (JPEG, PNG, WebP) within 5MB limit.',
    guide: 'Upload item photos in post creator; verify upload progress and 200 OK response.',
  },
  {
    id: 'posts-preview-image',
    category: 'func-posts',
    priority: 'important',
    title: 'Preview Uploaded Image Thumbnail',
    description: 'Uploaded image renders as preview in form and as thumbnail card in feed.',
    guide: 'Confirm image renders correctly before submitting post and after posting.',
  },
  {
    id: 'posts-location-works',
    category: 'func-posts',
    priority: 'important',
    title: 'Location & Barangay Tagging Works',
    description: 'Item displays accurate municipality, barangay, and distance or map pin.',
    guide: 'Verify location metadata is saved with barangay and city of San Fernando.',
  },
  {
    id: 'posts-favorite-works',
    category: 'func-posts',
    priority: 'recommended',
    title: 'Favorite / Save Item Works',
    description: 'Clicking heart icon saves item to /saved-items and updates saved count.',
    guide: 'Toggle favorite on item; check /saved-items to confirm item is listed.',
  },
  {
    id: 'posts-report-post',
    category: 'func-posts',
    priority: 'important',
    title: 'Report Post Works',
    description: 'Clicking "Report Item" opens report modal and submits report to admin queue.',
    guide: 'Submit test report on post; check admin /admin/reports to confirm it was logged.',
  },
  {
    id: 'posts-removed-disappear',
    category: 'func-posts',
    priority: 'critical',
    title: 'Removed & Reserved Posts Handled Correctly',
    description: 'Items marked completed, reserved, or removed update their badge and availability.',
    guide: 'Reserve an item; confirm "Reserved" badge shows in browse feed.',
  },

  // ==========================================
  // 5. FUNCTIONALITY: REQUESTS & DONATIONS (6 items)
  // ==========================================
  {
    id: 'req-request-item',
    category: 'func-requests',
    priority: 'critical',
    title: 'Request an Item / Donation',
    description: 'Neighbor can click "Request Item" on a post and submit a request message.',
    guide: 'Submit donation claim on an item; confirm success modal appears.',
  },
  {
    id: 'req-opens-conversation',
    category: 'func-requests',
    priority: 'critical',
    title: 'Request Opens Correct Direct Conversation',
    description: 'Submitting request automatically creates or navigates to direct chat with poster.',
    guide: 'Verify redirect to /messages/:convId with item card preview in header.',
  },
  {
    id: 'req-poster-receives-notification',
    category: 'func-requests',
    priority: 'critical',
    title: 'Poster Receives Request Notification',
    description: 'Item poster receives both an in-app notification and email alert regarding request.',
    guide: 'Check recipient notifications bell and mailbox for donation request notice.',
  },
  {
    id: 'req-status-updates',
    category: 'func-requests',
    priority: 'critical',
    title: 'Request Status Transitions (Pending → Accepted / Declined)',
    description: 'Poster can accept or decline request; status updates accurately for both parties.',
    guide: 'Accept request in chat or request management; confirm status changes to ACCEPTED.',
  },
  {
    id: 'req-cancel-request',
    category: 'func-requests',
    priority: 'important',
    title: 'Requester Can Cancel Request',
    description: 'Requester can cancel a pending claim if they no longer need the item.',
    guide: 'Click cancel on active request; verify status updates to CANCELLED.',
  },
  {
    id: 'req-removed-display',
    category: 'func-requests',
    priority: 'important',
    title: 'Cancelled / Completed Requests Display Correctly',
    description: 'Lists in /requests tab separate active from completed or cancelled requests.',
    guide: 'Inspect /requests page under different tab filters.',
  },

  // ==========================================
  // 6. FUNCTIONALITY: MESSAGING (14 items)
  // ==========================================
  {
    id: 'msg-two-user-send',
    category: 'func-messaging',
    priority: 'critical',
    title: 'User A Sends Message to User B',
    description: 'User A types and sends message in conversation; message appears immediately in thread.',
    guide: 'Send message from Account A in one browser window.',
  },
  {
    id: 'msg-two-user-receive',
    category: 'func-messaging',
    priority: 'critical',
    title: 'User B Receives Message in Real-Time',
    description: 'User B in separate window receives message without needing manual page refresh.',
    guide: 'Verify incoming message appears in Account B’s window via WebSocket/polling.',
  },
  {
    id: 'msg-two-user-reply',
    category: 'func-messaging',
    priority: 'critical',
    title: 'User B Replies & Conversation Flows Both Ways',
    description: 'Two-way bidirectional communication functions smoothly.',
    guide: 'Reply from User B; confirm User A receives the reply in real-time.',
  },
  {
    id: 'msg-typing-indicator',
    category: 'func-messaging',
    priority: 'important',
    title: 'Typing Indicator Works',
    description: 'When User A types, User B sees "[User] is typing..." animated indicator.',
    guide: 'Type in User A input box; confirm typing indicator appears in User B chat.',
  },
  {
    id: 'msg-online-presence',
    category: 'func-messaging',
    priority: 'important',
    title: 'Online / Offline Status Indicator Works',
    description: 'Green dot shows for active neighbors; offline indicator shows when logged out.',
    guide: 'Verify online indicator reflects partner’s presence state.',
  },
  {
    id: 'msg-seen-status',
    category: 'func-messaging',
    priority: 'important',
    title: 'Seen / Read Receipt Works',
    description: 'When partner views message, status updates from "Sent" to "Seen".',
    guide: 'Open unread conversation; confirm double-check/seen timestamp updates.',
  },
  {
    id: 'msg-reactions',
    category: 'func-messaging',
    priority: 'recommended',
    title: 'Message Reactions Work',
    description: 'Users can react with emoji (thumbs up, heart, smile) to specific messages.',
    guide: 'Hover message and click reaction emoji; verify reaction pill attaches to message.',
  },
  {
    id: 'msg-reply-to-message',
    category: 'func-messaging',
    priority: 'recommended',
    title: 'Reply-To (Quote) Message Works',
    description: 'Clicking reply quotes original message above input bar and links in thread.',
    guide: 'Reply to specific message; confirm quoted snippet renders above message bubble.',
  },
  {
    id: 'msg-edit-message',
    category: 'func-messaging',
    priority: 'important',
    title: 'Edit Message Works (Within 5 Minutes)',
    description: 'Sender can edit text of recently sent message; "(edited)" tag appears.',
    guide: 'Edit message within 5 minutes; confirm text updates and shows edited tag.',
  },
  {
    id: 'msg-edit-expires',
    category: 'func-messaging',
    priority: 'important',
    title: 'Edit Expires After 5 Minutes',
    description: 'Messages older than 5 minutes no longer show edit option in action menu.',
    guide: 'Verify edit button disappears or errors for messages older than 5 minutes.',
  },
  {
    id: 'msg-unsend-message',
    category: 'func-messaging',
    priority: 'important',
    title: 'Unsend Message Works (Within 5 Minutes)',
    description: 'Sender can unsend a message within 5 minutes; message is removed for both users.',
    guide: 'Click unsend on newly sent message; verify message bubble disappears for both users.',
  },
  {
    id: 'msg-unsend-expires',
    category: 'func-messaging',
    priority: 'important',
    title: 'Unsend Expires After 5 Minutes',
    description: 'Messages older than 5 minutes cannot be unsent.',
    guide: 'Verify unsend button is disabled or hidden on messages older than 5 minutes.',
  },
  {
    id: 'msg-refresh-persists',
    category: 'func-messaging',
    priority: 'critical',
    title: 'Browser Refresh Does Not Delete Messages',
    description: 'Hard reloading browser preserves entire conversation history and attachments.',
    guide: 'Refresh browser window in /messages; confirm entire conversation history reloads intact.',
  },
  {
    id: 'msg-database-persistence',
    category: 'func-messaging',
    priority: 'critical',
    title: 'Messages Persist in MySQL Database',
    description: 'Messages, reactions, and attachments are saved permanently in MySQL schema.',
    guide: 'Inspect messages table in DB to confirm message records exist.',
  },

  // ==========================================
  // 7. FUNCTIONALITY: NOTIFICATIONS (8 items)
  // ==========================================
  {
    id: 'notif-registration',
    category: 'func-notifications',
    priority: 'critical',
    title: 'Registration Confirmation Email Delivered',
    description: 'Verify welcome/pending notification is received in applicant inbox.',
    guide: 'Check applicant mailbox after registration; confirm receipt.',
  },
  {
    id: 'notif-approval',
    category: 'func-notifications',
    priority: 'critical',
    title: 'Account Approval Notification Delivered',
    description: 'Verify account approved email arrives with direct sign-in button.',
    guide: 'Approve user in admin; check applicant mailbox for approval notification.',
  },
  {
    id: 'notif-rejection',
    category: 'func-notifications',
    priority: 'important',
    title: 'Account Rejection Notification Delivered',
    description: 'Verify rejection notice explains reason and instructions for resubmitting.',
    guide: 'Reject user; check applicant mailbox for rejection details.',
  },
  {
    id: 'notif-password-reset',
    category: 'func-notifications',
    priority: 'critical',
    title: 'Password Reset Email Delivered',
    description: 'Verify password reset link arrives with secure reset button and 1-hour expiry notice.',
    guide: 'Trigger forgot password; verify reset email arrives within 30 seconds.',
  },
  {
    id: 'notif-new-message',
    category: 'func-notifications',
    priority: 'important',
    title: 'New Chat Message Notification Delivered',
    description: 'Offline recipient receives email alert notifying them of unread community chat message.',
    guide: 'Send message to offline user; verify email alert arrives.',
  },
  {
    id: 'notif-suspension',
    category: 'func-notifications',
    priority: 'important',
    title: 'Account Suspension Notification Delivered',
    description: 'Suspending an account dispatches notification explaining temporary/permanent suspension.',
    guide: 'Suspend test user in admin panel; verify suspension notice is received.',
  },
  {
    id: 'notif-post-removal',
    category: 'func-notifications',
    priority: 'important',
    title: 'Post Removal Notification Delivered',
    description: 'Admin deletion of violating content alerts owner with moderation rationale.',
    guide: 'Remove post in admin; verify author receives removal notice.',
  },
  {
    id: 'notif-request-received',
    category: 'func-notifications',
    priority: 'important',
    title: 'Item Request Notification Delivered',
    description: 'Item owner receives email alert when another neighbor requests their posted donation.',
    guide: 'Claim item as User B; check User A’s email inbox for request alert.',
  },

  // ==========================================
  // 8. FUNCTIONALITY: REPORTS (8 items)
  // ==========================================
  {
    id: 'rep-user-can-report-post',
    category: 'func-reports',
    priority: 'critical',
    title: 'User Can Report a Post',
    description: 'Neighbors can report inappropriate posts with predefined violation categories and notes.',
    guide: 'Click report on item; submit report with category "Misleading / Spam".',
  },
  {
    id: 'rep-user-can-report-user',
    category: 'func-reports',
    priority: 'important',
    title: 'User Can Report Another User / Neighbor',
    description: 'Neighbor can file conduct reports against abusive profiles or scammers.',
    guide: 'Submit report against test profile; confirm confirmation toast.',
  },
  {
    id: 'rep-appears-in-admin',
    category: 'func-reports',
    priority: 'critical',
    title: 'Report Appears in Admin Moderation Dashboard',
    description: 'Submitted reports immediately appear under /admin/reports with high-priority flagging.',
    guide: 'Navigate to /admin/reports; confirm newly submitted report is visible.',
  },
  {
    id: 'rep-admin-can-review',
    category: 'func-reports',
    priority: 'critical',
    title: 'Admin Can Review Report Details',
    description: 'Admin can open report drawer to inspect reported content, reporter reason, and history.',
    guide: 'Click report card; verify drawer displays complete details and content link.',
  },
  {
    id: 'rep-admin-can-resolve',
    category: 'func-reports',
    priority: 'critical',
    title: 'Admin Can Resolve Report with Action',
    description: 'Admin can mark report resolved (e.g., removing content or suspending offender).',
    guide: 'Click "Resolve & Take Action"; confirm report moves to Resolved list.',
  },
  {
    id: 'rep-admin-can-dismiss',
    category: 'func-reports',
    priority: 'important',
    title: 'Admin Can Dismiss False Reports',
    description: 'Admin can dismiss invalid or malicious reports with explanation note.',
    guide: 'Click "Dismiss Report"; verify report moves to Dismissed list.',
  },
  {
    id: 'rep-reported-content-handled',
    category: 'func-reports',
    priority: 'critical',
    title: 'Reported Content Handled Correctly',
    description: 'Content flagged as dangerous can be immediately unlisted or hidden by moderators.',
    guide: 'Verify post removal action removes posting from public feed.',
  },
  {
    id: 'rep-reporter-notified',
    category: 'func-reports',
    priority: 'recommended',
    title: 'Reporter Receives Status Update',
    description: 'Reporter can see resolution status in notifications bell.',
    guide: 'Check reporter notification inbox for resolution confirmation.',
  },

  // ==========================================
  // 9. DATABASE (11 items)
  // ==========================================
  {
    id: 'db-production-configured',
    category: 'database',
    priority: 'critical',
    title: 'Production Database Configured in DATABASE_URL',
    description: 'Verify backend connects to production MySQL instance with proper character set (utf8mb4).',
    guide: 'Check /api/db-health returns status: "connected" with production database name.',
  },
  {
    id: 'db-credentials-protected',
    category: 'database',
    priority: 'critical',
    title: 'Database Credentials Protected in .env',
    description: 'Database passwords and connection strings are stored solely in environment variables.',
    guide: 'Confirm no hardcoded database passwords exist in source files.',
  },
  {
    id: 'db-no-dev-database',
    category: 'database',
    priority: 'critical',
    title: 'No Development Database in Production',
    description: 'Production deployment does not point to local or test staging databases.',
    guide: 'Verify Render / server environment variables specify dedicated production host.',
  },
  {
    id: 'db-no-junk-mock-data',
    category: 'database',
    priority: 'important',
    title: 'No Unnecessary Mock Data Remains',
    description: 'Clear placeholder test records, fake accounts, or lorem ipsum entries before launch.',
    guide: 'Review users, items, and conversations tables for test junk.',
  },
  {
    id: 'db-production-demo-records',
    category: 'database',
    priority: 'important',
    title: 'Only Intended Production & Seed Records Exist',
    description: 'Verify essential seed data (categories, conditions, roles, admin accounts) exists.',
    guide: 'Ensure ItemCategory has 8+ standard categories and Role has admin and user entries.',
  },
  {
    id: 'db-foreign-keys-work',
    category: 'database',
    priority: 'critical',
    title: 'Foreign Keys & Constraints Active',
    description: 'MySQL foreign key constraints enforce referential integrity across all 3NF tables.',
    guide: 'Verify cascades and foreign keys on user_id, item_id, conversation_id.',
  },
  {
    id: 'db-relationships-work',
    category: 'database',
    priority: 'critical',
    title: 'ORM Relationships & Joined Loads Function',
    description: 'SQLAlchemy joinedload correctly hydrates user profile, status, roles, and item images.',
    guide: 'Verify query results contain populated nested profile and role objects.',
  },
  {
    id: 'db-duplicates-prevented',
    category: 'database',
    priority: 'critical',
    title: 'Duplicate Records Prevented by Unique Indexes',
    description: 'Unique constraints on email, username, and token hashes prevent duplicate records.',
    guide: 'Attempt registering existing email; confirm MySQL unique constraint/HTTP 400 triggers.',
  },
  {
    id: 'db-errors-handled-safely',
    category: 'database',
    priority: 'critical',
    title: 'Database Errors Handled Safely',
    description: 'Database exceptions trigger session rollback and return generic 500 error messages.',
    guide: 'Confirm no raw SQL tracebacks are leaked to API consumers.',
  },
  {
    id: 'db-backups-exist',
    category: 'database',
    priority: 'critical',
    title: 'Database Backups Exist & Automated',
    description: 'Backup scripts (backup.py / backup.sh) run on schedule and output timestamped dumps.',
    guide: 'Run python backend/db/backup.py; confirm successful SQL dump generated in backups/.',
  },
  {
    id: 'db-restoration-tested',
    category: 'database',
    priority: 'important',
    title: 'Database Restoration Has Been Tested',
    description: 'Verify a generated backup SQL dump can be cleanly restored to a fresh test database.',
    guide: 'Test importing backup dump using mysql < backup.sql into a scratch database.',
  },

  // ==========================================
  // 10. ADMIN SECURITY (8 items)
  // ==========================================
  {
    id: 'admin-sec-normal-user-blocked',
    category: 'admin-security',
    priority: 'critical',
    title: 'Normal User Cannot Access Admin Dashboard',
    description: 'Attempting to navigate to /admin with a standard user role redirects to /dashboard.',
    guide: 'Sign in as standard neighbor; enter /admin in URL bar; confirm redirection.',
  },
  {
    id: 'admin-sec-apis-blocked',
    category: 'admin-security',
    priority: 'critical',
    title: 'Normal User Cannot Call Admin APIs',
    description: 'Direct HTTP calls to /api/admin/* endpoints without admin role return 403 Forbidden.',
    guide: 'Send curl GET /api/admin/users with standard user token/ID; confirm 403 response.',
  },
  {
    id: 'admin-sec-approve-blocked',
    category: 'admin-security',
    priority: 'critical',
    title: 'Normal User Cannot Approve Other Users',
    description: 'Unauthorized requests to approve identity verifications are rejected.',
    guide: 'Confirm /api/admin/verifications/:id/approve rejects non-admin callers.',
  },
  {
    id: 'admin-sec-suspend-blocked',
    category: 'admin-security',
    priority: 'critical',
    title: 'Normal User Cannot Suspend Other Users',
    description: 'Suspension endpoints are strictly locked to administrator privileges.',
    guide: 'Confirm /api/admin/users/:id/suspend rejects non-admin callers.',
  },
  {
    id: 'admin-sec-remove-posts-blocked',
    category: 'admin-security',
    priority: 'critical',
    title: 'Normal User Cannot Remove Other Users’ Posts',
    description: 'Standard neighbors can only delete items where owner_id matches their own ID.',
    guide: 'Attempt deleting another user’s item via DELETE /api/items/:id; confirm 403 Forbidden.',
  },
  {
    id: 'admin-sec-manage-reports-blocked',
    category: 'admin-security',
    priority: 'critical',
    title: 'Normal User Cannot Manage Moderation Reports',
    description: 'Only admins can review, resolve, or dismiss moderation reports.',
    guide: 'Attempt calling /api/reports/:id/resolve without admin role; confirm 403 response.',
  },
  {
    id: 'admin-sec-unauthenticated-blocked',
    category: 'admin-security',
    priority: 'critical',
    title: 'Unauthenticated Visitors Cannot Access Protected Pages',
    description: 'Navigating to /admin, /dashboard, /post-item, or /messages without login redirects to /login.',
    guide: 'Open incognito window; navigate to /admin; confirm redirection to /login.',
  },
  {
    id: 'admin-sec-frontend-role-tampering',
    category: 'admin-security',
    priority: 'critical',
    title: 'Tampering with Frontend Role Does Not Grant Admin Access',
    description: 'Manually editing localStorage role to "admin" does not authorize backend API calls.',
    guide: 'Edit localStorage auth-storage to role: "admin"; attempt admin actions; backend must reject.',
  },

  // ==========================================
  // 11. UI / UX & RESPONSIVENESS (10 items)
  // ==========================================
  {
    id: 'ui-desktop-viewports',
    category: 'ui-ux',
    priority: 'important',
    title: 'Desktop Viewports (1280px, 1440px, 1920px)',
    description: 'Test all main screens on wide desktop monitors for optimal layout, grid alignment, and spacing.',
    guide: 'Test on 1280px, 1440px, and 1920px viewports; verify no awkward stretched containers.',
  },
  {
    id: 'ui-tablet-viewports',
    category: 'ui-ux',
    priority: 'important',
    title: 'Tablet Viewports (768px, 1024px)',
    description: 'Test responsive tablet layouts (iPad, portrait/landscape tablets) for navbar collapse and grids.',
    guide: 'Test on 768px and 1024px viewports; verify tablet navigation functions smoothly.',
  },
  {
    id: 'ui-mobile-viewports',
    category: 'ui-ux',
    priority: 'critical',
    title: 'Mobile Viewports (320px, 375px, 390px, 412px)',
    description: 'Test mobile layouts on standard phone screens (iPhone, Galaxy, Pixel) without horizontal scrolling.',
    guide: 'Test on 320px (SE), 375px, 390px (iPhone 14/15), and 412px (Android); confirm clean fit.',
  },
  {
    id: 'ui-no-horizontal-scrolling',
    category: 'ui-ux',
    priority: 'critical',
    title: 'No Unwanted Horizontal Scrollbars',
    description: 'Entire application has overflow-x hidden on root container; no sideways page shifting.',
    guide: 'Inspect document.documentElement.scrollWidth <= window.innerWidth on all pages.',
  },
  {
    id: 'ui-navigation-works',
    category: 'ui-ux',
    priority: 'critical',
    title: 'Navigation Header & Mobile Drawer Function',
    description: 'Desktop header links and mobile hamburger slide-out drawer work on all pages.',
    guide: 'Open mobile drawer; test every route link; verify drawer closes upon navigation.',
  },
  {
    id: 'ui-buttons-clickable',
    category: 'ui-ux',
    priority: 'critical',
    title: 'Buttons Visible & Touch Targets Sized Correctly',
    description: 'All buttons have minimum 44x44px touch targets on mobile and clear hover/active states.',
    guide: 'Verify buttons are easy to tap on touchscreen devices without accidental misclicks.',
  },
  {
    id: 'ui-modals-fit-screen',
    category: 'ui-ux',
    priority: 'important',
    title: 'Modals & Drawers Fit Screen',
    description: 'Verification dialogs, image previews, and report modals fit within mobile viewports.',
    guide: 'Open report modal and photo preview modal on mobile; verify content scrolls cleanly.',
  },
  {
    id: 'ui-forms-fit-screen',
    category: 'ui-ux',
    priority: 'important',
    title: 'Forms & Inputs Fit Screen',
    description: 'Registration, post creator, and login forms do not overflow viewport; virtual keyboard works.',
    guide: 'Focus inputs on mobile; ensure virtual keyboard does not obscure submit buttons.',
  },
  {
    id: 'ui-messaging-mobile',
    category: 'ui-ux',
    priority: 'critical',
    title: 'Messaging Interface Works on Mobile',
    description: 'Chat list and active conversation switch seamlessly on mobile without overlapping.',
    guide: 'Test opening a conversation on mobile; confirm back button returns to chat list.',
  },
  {
    id: 'ui-admin-small-screens',
    category: 'ui-ux',
    priority: 'important',
    title: 'Admin Dashboard Usable on Small Screens',
    description: 'Admin tables have horizontal scroll wrappers and cards scale on tablet/laptop screens.',
    guide: 'Check /admin/approvals on 768px viewport; verify applicant cards render legibly.',
  },

  // ==========================================
  // 12. LOADING, EMPTY & ERROR STATES (6 items)
  // ==========================================
  {
    id: 'state-slow-internet',
    category: 'states',
    priority: 'important',
    title: 'Slow Internet / Loading Skeletons',
    description: 'Pages display clean spinner or skeleton placeholders while fetching data. Never blank screens.',
    guide: 'Throttle network to "Slow 3G" in DevTools; verify loading states appear smoothly.',
  },
  {
    id: 'state-failed-api',
    category: 'states',
    priority: 'important',
    title: 'Failed API Request Error States',
    description: 'When an endpoint fails or server disconnects, user sees helpful error message with retry button.',
    guide: 'Simulate API failure; verify "Unable to load data. Please try again." banner appears.',
  },
  {
    id: 'state-empty-results',
    category: 'states',
    priority: 'important',
    title: 'Empty Search & Database Results',
    description: 'When search has 0 results or category is empty, friendly graphic and message display.',
    guide: 'Search for nonsense keyword "xyz123"; verify "No items found" message with clear search button.',
  },
  {
    id: 'state-expired-session',
    category: 'states',
    priority: 'critical',
    title: 'Expired Session Handled Gracefully',
    description: 'When session expires or 401 Unauthorized is returned, user is safely redirected to login.',
    guide: 'Clear auth token and trigger API request; verify redirect to /login with notification.',
  },
  {
    id: 'state-server-error',
    category: 'states',
    priority: 'important',
    title: 'Server Error (500) Handled Safely',
    description: '500 Internal Server Errors show friendly community error card without crashing React tree.',
    guide: 'Verify error boundaries catch component render exceptions.',
  },
  {
    id: 'state-offline-connection',
    category: 'states',
    priority: 'important',
    title: 'Offline Connection Handled',
    description: 'When user disconnects from Wi-Fi, offline banner or toast alerts them to check connection.',
    guide: 'Set browser offline in DevTools; verify offline toast appears.',
  },

  // ==========================================
  // 13. PRODUCTION CHECKS (13 items)
  // ==========================================
  {
    id: 'prod-debug-off',
    category: 'production',
    priority: 'critical',
    title: 'Debug Mode OFF in Production',
    description: 'DEBUG=false in backend configuration; verbose debug logs and Swagger UI are hidden.',
    guide: 'Verify /docs and /redoc return 404 in production environment.',
  },
  {
    id: 'prod-api-url-configured',
    category: 'production',
    priority: 'critical',
    title: 'Production API URL Configured',
    description: 'Frontend connects to production backend URL (e.g., https://bayanihanhub-api.onrender.com).',
    guide: 'Inspect vercel.json rewrites or frontend VITE_API_URL to ensure production domain is used.',
  },
  {
    id: 'prod-db-configured',
    category: 'production',
    priority: 'critical',
    title: 'Production Database Configured',
    description: 'DATABASE_URL points to live production MySQL database.',
    guide: 'Verify production database host, credentials, and connection pool.',
  },
  {
    id: 'prod-env-vars',
    category: 'production',
    priority: 'critical',
    title: 'Production Environment Variables Configured',
    description: 'All mandatory env vars (JWT_SECRET, SMTP_HOST, SMTP_USER, CORS_ORIGINS) are configured.',
    guide: 'Compare .env.example against host provider dashboard (Vercel / Render).',
  },
  {
    id: 'prod-env-not-committed',
    category: 'production',
    priority: 'critical',
    title: '.env Files Excluded from Git',
    description: 'Confirm .env, .env.local, and .env.production are excluded in .gitignore.',
    guide: 'Run git status to confirm no .env files are tracked or uncommitted.',
  },
  {
    id: 'prod-https-enabled',
    category: 'production',
    priority: 'critical',
    title: 'HTTPS Certificate Active',
    description: 'SSL/TLS certificates are active with valid trust chain and no mixed-content warnings.',
    guide: 'Inspect SSL padlock in browser address bar on live deployment.',
  },
  {
    id: 'prod-domain-configured',
    category: 'production',
    priority: 'important',
    title: 'Custom Domain & DNS Configured',
    description: 'Domain records (A, CNAME, ALIAS) resolve properly to production hosts.',
    guide: 'Test domain resolution via ping or dig.',
  },
  {
    id: 'prod-cors-configured',
    category: 'production',
    priority: 'critical',
    title: 'CORS Configured Strictly for Production',
    description: 'CORS_ORIGINS restricts access to authorized frontend domains (no open * wildcard).',
    guide: 'Verify CORS headers in render.yaml and config.py.',
  },
  {
    id: 'prod-secure-cookies',
    category: 'production',
    priority: 'important',
    title: 'Secure Session / Storage Settings',
    description: 'Session parameters set Secure and SameSite flags.',
    guide: 'Inspect cookies/tokens in DevTools storage inspector.',
  },
  {
    id: 'prod-error-logging',
    category: 'production',
    priority: 'important',
    title: 'Error Logging & Terminal Engine Active',
    description: 'Server logs error diagnostics to logger without exposing sensitive client data.',
    guide: 'Check server log output on Render / hosting dashboard.',
  },
  {
    id: 'prod-no-debug-messages',
    category: 'production',
    priority: 'important',
    title: 'No Debug Messages Visible to Users',
    description: 'Console log spam and internal error strings are stripped from production builds.',
    guide: 'Open DevTools console in production build; confirm no developer dump logs.',
  },
  {
    id: 'prod-no-test-accounts',
    category: 'production',
    priority: 'important',
    title: 'Test Accounts Removed / Cleaned',
    description: 'Remove dummy test passwords, scratch accounts, and mock identity cards.',
    guide: 'Confirm only authorized seed accounts (Jeho admin) exist.',
  },
  {
    id: 'prod-no-dev-endpoints',
    category: 'production',
    priority: 'critical',
    title: 'No Insecure Development Endpoints Exposed',
    description: 'Endpoints used for local mock generation or DB drop are disabled or deleted.',
    guide: 'Verify no drop-db or seed-fake endpoints are accessible.',
  },

  // ==========================================
  // 14. PERFORMANCE (9 items)
  // ==========================================
  {
    id: 'perf-images-optimized',
    category: 'performance',
    priority: 'important',
    title: 'Images Optimized & Lazy-Loaded',
    description: 'Images have loading="lazy" attributes and responsive srcset where appropriate.',
    guide: 'Inspect img tags in browse feed for loading="lazy".',
  },
  {
    id: 'perf-large-images-compressed',
    category: 'performance',
    priority: 'important',
    title: 'Large Images Compressed Before Upload',
    description: 'Item and biometric photos are scaled or compressed to avoid huge network transfers.',
    guide: 'Verify uploaded image sizes are typically < 500KB.',
  },
  {
    id: 'perf-upload-size-limits',
    category: 'performance',
    priority: 'critical',
    title: 'Uploaded Files Have Strict Size Limits',
    description: 'Enforce 5MB limit for item photos and 10MB limit for chat attachments.',
    guide: 'Attempt uploading 15MB file; verify immediate 413 Payload Too Large error.',
  },
  {
    id: 'perf-api-responses-small',
    category: 'performance',
    priority: 'important',
    title: 'API Responses Are Reasonably Sized',
    description: 'Endpoints return paginated or trimmed JSON payloads (< 200KB per response).',
    guide: 'Inspect Network tab payload size for /api/items; ensure under 100KB.',
  },
  {
    id: 'perf-no-unnecessary-requests',
    category: 'performance',
    priority: 'important',
    title: 'No Unnecessary API Requests',
    description: 'Avoid polling or refetching loops that flood the backend.',
    guide: 'Open Network tab on static page; ensure requests stop after initial page load.',
  },
  {
    id: 'perf-no-repeated-requests',
    category: 'performance',
    priority: 'critical',
    title: 'No Repeated API Loops Caused by React Hooks',
    description: 'Ensure useEffect dependency arrays do not cause infinite fetch re-renders.',
    guide: 'Observe Network tab for 10 seconds; confirm 0 continuous looping API calls.',
  },
  {
    id: 'perf-db-queries-efficient',
    category: 'performance',
    priority: 'important',
    title: 'Database Queries Are Indexed & Efficient',
    description: 'Indexed columns (user_id, item_id, account_status_id) prevent full table scans.',
    guide: 'Inspect schema indexes on foreign keys and search columns.',
  },
  {
    id: 'perf-pages-load-fast',
    category: 'performance',
    priority: 'important',
    title: 'Pages Load Within Reasonable Time (< 2.5s LCP)',
    description: 'Lighthouse / Web Vitals score is within acceptable parameters on 4G connections.',
    guide: 'Run Chrome DevTools Lighthouse audit on home and browse pages.',
  },
  {
    id: 'perf-messaging-traffic',
    category: 'performance',
    priority: 'important',
    title: 'Messaging Does Not Create Excessive Requests',
    description: 'Polling intervals or WebSocket heartbeats are throttled sensibly.',
    guide: 'Monitor chat window idle traffic; verify reasonable polling cadence.',
  },

  // ==========================================
  // 15. SEO & BASIC WEB REQUIREMENTS (8 items)
  // ==========================================
  {
    id: 'seo-page-title',
    category: 'seo',
    priority: 'important',
    title: 'Accurate Page Titles on Every Route',
    description: 'Document head contains contextual titles (e.g. "Community Items | Bayanihan Hub").',
    guide: 'Inspect tab titles across home, browse, post item, admin, and login.',
  },
  {
    id: 'seo-meta-description',
    category: 'seo',
    priority: 'important',
    title: 'Compelling Meta Descriptions',
    description: 'Search engines and social share previews receive meaningful summaries.',
    guide: 'Check meta name="description" tag in HTML source.',
  },
  {
    id: 'seo-favicon',
    category: 'seo',
    priority: 'recommended',
    title: 'Favicon & App Icon Configured',
    description: 'Bayanihan Hub heart-hands logo favicon appears cleanly in browser tabs.',
    guide: 'Verify /favicon.ico and /Logo1Revise.png render in browser tab.',
  },
  {
    id: 'seo-heading-structure',
    category: 'seo',
    priority: 'important',
    title: 'Proper Heading Hierarchy (h1, h2, h3)',
    description: 'Each page has exactly one h1 tag followed by logical h2 and h3 subheadings.',
    guide: 'Audit heading structure with accessibility tools; ensure no skipped levels.',
  },
  {
    id: 'seo-robots-txt',
    category: 'seo',
    priority: 'recommended',
    title: 'robots.txt Configured',
    description: 'Instruct search bots to crawl public pages and avoid crawling /admin or /api routes.',
    guide: 'Verify public/robots.txt allows / and disallows /admin.',
  },
  {
    id: 'seo-sitemap-xml',
    category: 'seo',
    priority: 'recommended',
    title: 'sitemap.xml Configured',
    description: 'Sitemap lists landing, browse, about, and community guidelines pages.',
    guide: 'Verify sitemap.xml exists in public directory.',
  },
  {
    id: 'seo-open-graph',
    category: 'seo',
    priority: 'recommended',
    title: 'Open Graph & Social Share Metadata',
    description: 'og:title, og:image, and og:description tags format nicely on Facebook/Twitter.',
    guide: 'Inspect og: tags in index.html and SEO components.',
  },
  {
    id: 'seo-404-page',
    category: 'seo',
    priority: 'important',
    title: 'Custom 404 Not Found Page',
    description: 'Navigating to unknown URL displays branded Bayanihan Hub 404 page with return home button.',
    guide: 'Navigate to /some-random-broken-path; verify custom 404 page displays.',
  },

  // ==========================================
  // 16. FINAL DEPLOYMENT CHECK (3 items)
  // ==========================================
  {
    id: 'final-all-critical-cleared',
    category: 'final-check',
    priority: 'critical',
    title: 'All Critical Security & Functional Checks Cleared',
    description: 'Confirm 100% of Critical checklist items are marked complete with zero open vulnerabilities.',
    guide: 'Check the Deployment Readiness banner at the top of the dashboard.',
  },
  {
    id: 'final-staging-smoke-test',
    category: 'final-check',
    priority: 'critical',
    title: 'Final Staging Smoke Test Executed',
    description: 'Run through full user registration, admin approval, item posting, and chat flow on live staging.',
    guide: 'Perform end-to-end user journey in staging environment.',
  },
  {
    id: 'final-stakeholder-greenlight',
    category: 'final-check',
    priority: 'important',
    title: 'Release Tagged & Stakeholder Greenlight',
    description: 'Git commit tagged with version release (e.g. v1.0.0-prod) and deployment authorized.',
    guide: 'Verify git commit is pushed to origin/main and deployment builds are green.',
  },
];
